services:
  jekyll:
    image: amirpourmand/al-folio:latest
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
